name: Fill The Google Forms
on:
  workflow_dispatch:
    inputs:
      date:
        description: "Date to fill"
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Get current time
        uses: josStorer/get-current-time@v2.0.2
        id: current-time
        with:
          format: YYYYMMDD-HHmmss
          utcOffset: "+07:00"
        
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          start: npx cypress run
          env: FORM=test,N=14${{ github.event.inputs.date != '' && format(',DATE_NOW={0}', github.event.inputs.date) }}
          
      - name: Upload Test Video (If failed happens)
        if: failure()
        uses: actions/upload-artifact@v3.1.0
        with:
          name: Failed Reports-${{ steps.current-time.outputs.formattedTime }}
          path: |
            ${{ github.workspace }}/cypress/videos/gform.cy.js.mp4
            ${{ github.workspace }}/cypress/screenshots/gform.cy.js/Google Forms Automation -- Iteration 1 (failed).png
